In [1]:
import sys
sys.path.append('../../pyutils')

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import metrics
import utils

# Decorrelation

Let $X \in \mathbb{R}^{p*N}$ a matrix of $N$ observations with $p$ features. We suppose the matrix $X$ is centered.  
The goal of decorrelation is to transform $X$ into a new matrix with a diagonal covariance matrix.  
We need to find $W_D \in \mathbb{R}^{p*p}$ such that:
$$Y = W_D X$$
And the components of $Y$ are uncorrelated, that is:
$$D = \text{cov}(X)$$  

Let's define the covariance matrix of $X$ is:
$$\Sigma = \text{cov}(X) = E[XX^T] \approx \frac{1}{N} XX^T$$
$\Sigma$ is positive semi-definite, we can diagonalize it to get:
$$\Sigma = E^TDE$$
$$E^T\Sigma E=D$$  

Solving for $D = \text{cov}(Y)$, we get:
$$W_D = E^T$$

In [2]:
def decorr(X):
    C = X @ X.T
    d, E = np.linalg.eigh(C)
    return E.T

X = np.random.randn(4, 37)
X -= np.mean(X, axis=1, keepdims=True)
W = decorr(X)
Y = W @ X
print(Y.shape)
print(np.cov(Y, bias=True))

(4, 37)
[[ 4.73973045e-01 -1.96601688e-16 -4.43330745e-17 -2.56334903e-17]
 [-1.96601688e-16  9.46364391e-01  1.31403667e-16  4.79441863e-17]
 [-4.43330745e-17  1.31403667e-16  1.10494188e+00  1.32947986e-16]
 [-2.56334903e-17  4.79441863e-17  1.32947986e-16  1.22915718e+00]]


# Whitening

The goal of decorrelation is to transform $X$ into a new matrix with a unit diagonal covariance matrix.  
We need to find $W \in \mathbb{R}^{p*p}$ such that:
$$Y = W X$$
And the components of $Y$ are uncorrelated with unit variance, that is:
$$\text{cov}(X) = I_p$$

Using the decorrelation method above, we get $W_D$ and $Y$ has uncorrelated components. we just need to divide each component by it's standard deviation in order to get unit variance:
$$W = D^{-1/2}E^T$$

In [3]:
def whitening(X):
    N = X.shape[1]
    C = (X @ X.T) / N
    d, E = np.linalg.eigh(C)
    return E.T / np.sqrt(d).reshape(-1,1)
    

X = np.random.randn(4, 37)
X -= np.mean(X, axis=1, keepdims=True)
W = whitening(X)
Y = W @ X
print(Y.shape)
C = np.cov(Y, bias=True)
print(C)
print(metrics.tdist(C, np.eye(len(C))))

(4, 37)
[[ 1.00000000e+00 -1.06628553e-16  1.16918680e-16  8.92014010e-17]
 [-1.06628553e-16  1.00000000e+00  2.68953154e-16 -5.07991631e-18]
 [ 1.16918680e-16  2.68953154e-16  1.00000000e+00  3.20306287e-17]
 [ 8.92014010e-17 -5.07991631e-18  3.20306287e-17  1.00000000e+00]]
1.865246726087638e-15
