In [1]:
import sys
sys.path.append('..')

import numpy as np

import metrics

# Matrix similarity

Let $A$ and $B$ matrices of size $n*n$.  
$A$ and $B$ are similar if it exists an invertible matrix $P \in \mathbb{R}^{n*n}$ such that:
$$B = P^{-1}AP$$  

# Diagonalization

Let $A \in \mathbb{R}^{n*n}$
A is diagonalizable if it similar to a diagonal matrix.  
IE there is an invertible matrix $P \in \mathbb{R}^{n*n}$ such that $P^{-1}AP$ is diagonal.

The diagonilazation of matrix $A$ is:
$$P^{-1} A P = D$$
with $P \in \mathbb{R}^{n*n}$ is a matrix whose columns are the right eigenvectors of $A$.  
And $D \in \mathbb{R}^{n*n}$ a digonal matrix whose entries $D_{ii}$ is the eigeinvalue of $A$ corresponding to the eigeinvector $P_i$.  

The equation can be rewritten as:

$$A = PDP^{-1}$$

In [2]:
A = np.array([
    [1, 2, 1],
    [6, -1, 0],
    [-1, 2, 1]
])
d, P = np.linalg.eig(A)

print('A =\n', A)
print('P = \n', P)
print('diag(D)=\n', d)


D2 = np.linalg.inv(P) @ A @ P
print('P^-1AP=\n', D2)
print(metrics.tdist(np.diag(d), D2))

A2 = P @ np.diag(d) @ np.linalg.inv(P)
print('PDP^-1=\n', A2)
print(metrics.tdist(A, A2))

A =
 [[ 1  2  1]
 [ 6 -1  0]
 [-1  2  1]]
P = 
 [[ 0.60588985  0.28934634 -0.08122258]
 [ 0.73792101 -0.83016763 -0.41839386]
 [ 0.29727105  0.47655053  0.9046267 ]]
diag(D)=
 [ 3.92646107 -3.09123795  0.16477688]
P^-1AP=
 [[ 3.92646107e+00 -8.47397419e-16  5.54699765e-16]
 [ 3.69366844e-15 -3.09123795e+00  7.06300920e-16]
 [ 7.25290929e-16  3.97623940e-18  1.64776876e-01]]
4.431847301282925e-15
PDP^-1=
 [[ 1.00000000e+00  2.00000000e+00  1.00000000e+00]
 [ 6.00000000e+00 -1.00000000e+00  9.30119432e-16]
 [-1.00000000e+00  2.00000000e+00  1.00000000e+00]]
6.604835229600313e-15


# Square root of a matrix

Let $A$ and $B$ matrices of size $n*n$.  
Matrix $B$ is the square root of $A$ is $BB = A$  
The square root is denoted $B = A^{\frac{1}{2}}$  

A matrix may have several or no square root

If $A$ is diagonal, $B$ is a diagonal matrix whose entries are the square root of the diagonal entries of $A$

In [3]:
A = np.diag(np.random.randn(5)**2)
B = np.diag(np.sqrt(np.diag(A)))
print(metrics.tdist(A, B @ B))

0.0


If $A$ is diagonalizable with positive eigenvalues, the square root of $A$ is:

$$B = PD^{\frac{1}{2}}P^{-1}$$

In [4]:
A = np.array([
    [2, -2, 1],
    [-1, 3, -1],
    [2, -4, 3]
])
d, P = np.linalg.eig(A)

s = np.sqrt(d)
B = P @ np.diag(s) @ np.linalg.inv(P)
print(B)
print(metrics.tdist(B @ B, A))

[[ 1.28989795 -0.5797959   0.28989795]
 [-0.28989795  1.5797959  -0.28989795]
 [ 0.5797959  -1.15959179  1.5797959 ]]
1.900395703982448e-15


## Square root Inverse

$$A^{-\frac{1}{2}} = \text{inv}(A^{\frac{1}{2}})$$

$A^{-\frac{1}{2}}$ is the square root of $A^{-1}$:
$$A^{-\frac{1}{2}}A^{-\frac{1}{2}} = A^{-1}$$

If $A$ is diagonal, $A^{-\frac{1}{2}}$ is a diagonal matrix whose entries are the inverse square root of the diagonal entries of $A$

In [5]:
A = np.diag(3.8 * np.random.randn(5)**2 + 1.2)
B = np.diag(1 / np.sqrt(np.diag(A)))
print(metrics.tdist(np.linalg.inv(A), B @ B))

1.3615092990768423e-16


If $A$ is diagonalizable with positive eigenvalues, the inverse square root of $A$ is:

$$A^{-\frac{1}{2}} = PD^{-\frac{1}{2}}P^{-1}$$

In [6]:
A = np.array([
    [2, -2, 1],
    [-1, 3, -1],
    [2, -4, 3]
])
d, P = np.linalg.eig(A)

s = 1 / np.sqrt(d)
B = P @ np.diag(s) @ np.linalg.inv(P) 
print(B)
print(metrics.tdist(B @ B, np.linalg.inv(A)))

[[ 0.88164966  0.23670068 -0.11835034]
 [ 0.11835034  0.76329932  0.11835034]
 [-0.23670068  0.47340137  0.76329932]]
1.1025638216888958e-15


# Symmetric positive definite

Let $A$ a symmetric positive definite matrix. A is always diagonalizable:

$$P^T A P = D$$

With $P$, the marix of eigeinvectors, is an orthogonal matrix ($PP^T=P^TP=I$).

In [7]:
A = np.random.randn(4, 4)
A = A.T @ A
d, P = np.linalg.eigh(A)

print('A =\n', A)
print('P = \n', P)
print('diag(D)=\n', d)


D2 = np.linalg.inv(P) @ A @ P
print('P^-1AP=\n', D2)
print(metrics.tdist(np.diag(d), D2))

A2 = P @ np.diag(d) @ np.linalg.inv(P)
print('PDP^-1=\n', A2)
print(metrics.tdist(A, A2))

print(metrics.tdist(P @ P.T, np.eye(4)))
print(metrics.tdist(P.T @ P, np.eye(4)))

A =
 [[ 2.13807909 -1.14215066  1.56755208  1.207357  ]
 [-1.14215066  1.85032739  1.10732293 -1.24289598]
 [ 1.56755208  1.10732293  8.94491422  2.34793806]
 [ 1.207357   -1.24289598  2.34793806  3.25149354]]
P = 
 [[-0.46568542  0.73704243  0.43689363 -0.22142609]
 [-0.76962433 -0.12843571 -0.62414063 -0.04038729]
 [ 0.27298211  0.07109034 -0.2921085  -0.91383782]
 [-0.34102235 -0.65971122  0.57813931 -0.33799378]]
diag(D)=
 [ 0.21574085  1.40762424  4.31936039 10.24208878]
P^-1AP=
 [[ 2.15740848e-01  5.73055605e-16 -1.99199142e-15  4.43869011e-16]
 [ 3.62515265e-16  1.40762424e+00  1.68194542e-15 -6.16192384e-16]
 [-6.73945018e-17  5.39533885e-16  4.31936039e+00  4.73424125e-17]
 [-5.50967060e-16  6.45616442e-16  2.05683956e-16  1.02420888e+01]]
3.4793311321612236e-15
PDP^-1=
 [[ 2.13807909 -1.14215066  1.56755208  1.207357  ]
 [-1.14215066  1.85032739  1.10732293 -1.24289598]
 [ 1.56755208  1.10732293  8.94491422  2.34793806]
 [ 1.207357   -1.24289598  2.34793806  3.25149354]]
3.17

# Computing: Diagonalization of Non-Symetric matrix

## Implicitly-Shifted QR

The Implicitly-shifted QR algorithm is a method to compute the eigenvalues and eigenvectors of any square matrix

## Naive diagonalization

### Explicit QR algorithm: Find eigenvalues

- Let $A_0 = A$
- Iterate:
    - Compute the $QR$ factorization of $A$: $A_k = Q_k R_k$
    - Let $A_{k+1} = Q_k R_k$

As $k \to \infty$, $A_k$ converges to the Schur form of $A$, an upper-triangular matrix.
$$A_{k+1} = Q_k^{-1}A_kQ_k$$
So $A$, $A_1$, ..., $A_k$ are all similar, and thus they share the same eigenvalues.  
The eigenvalues of the upper-triangular matrix $A_k$ lie on the diagionals, they are the eigenvalues of $A$

In [8]:
def qr_algorithm(A, max_iters=1000):
    
    Ak = A.copy()
    for k in range(max_iters):
        # Compute norm below diagonal
        lnorm = np.linalg.norm(Ak - np.triu(Ak))
        if lnorm < 1e-10: break
        
        Q, R = np.linalg.qr(Ak)
        Ak = R @ Q
    
    return np.diag(Ak)

A = np.array([
    [2, -2, 1],
    [-1, 3, -1],
    [2, -4, 3]
])

d = qr_algorithm(A)
d2, _ = np.linalg.eig(A)

print(d)
print(d2)
print(metrics.tdist(d, d2))

[6. 1. 1.]
[6. 1. 1.]
6.3873580624876566e-12


### Compute the eigenvectors from a corresponding eigenvalue

$$Av = \lambda v$$
$$(A - \lambda I)v = \vec{0}$$

An orthogonal basis of $\text{Null}(A - \lambda I)$ is a set of eigenvectors for the eigeinvalue $\lambda$

In [65]:
def sv_rank(s):
    i = 0
    while i < len(s):
        if s[i] * s[i] < 1e-12:
            break
        i += 1
    return i

def find_evec(A, d):
    amd = A - np.eye(len(A)) * d
    U, s, VT = np.linalg.svd(amd)
    r = sv_rank(s)
    return VT[r:].T

def my_eig(A):
    d = qr_algorithm(A)
    vects = None
    for i in range(len(d)):
        if i > 0 and (d[i] - d[i-1])**2 < 1e-12:
            continue
        
        v = find_evec(A, d[i])
        if vects is None:
            vects = v
        else:
            vects = np.concatenate((vects, v), axis = 1)
    return d, vects
    
    
A = np.array([
    [2, -2, 1],
    [-1, 3, -1],
    [2, -4, 3]
])
d, P = my_eig(A)

for i in range(len(d)):
    print(metrics.tdist(A @ P[:, i], d[i] * P[:, i]))

print(metrics.tdist(np.linalg.inv(P) @ A @ P, np.diag(d)))
print(metrics.tdist(P @ np.diag(d) @ np.linalg.inv(P), A))

1.4812106129721512e-12
3.3603528951155397e-12
6.352821333422274e-12
6.725357375506194e-12
8.730925457289283e-12


# Computing: Diagonalization of Symetric matrix

## Jacobi Eigenvalue algorithm

The Jacobi eigenvalue algorithm is an iterative method to compute the eigenvalues and eigenvectors of a real symmetric matrix

### General algorithm

Let $A \in \mathbb{R}^{n*n}$ symmetric matrix

Let $A_0 = A$

$$A_{k+1} = R_k^T A_k R_k$$

with $R_k \in \mathbb{R}^{n*n}$ a givens rotation matrix.

All $A_k$ are symmetric with $A_k \to \Lambda$ as $k \to \infty$  

The algorithm converges to the diagonalization of $A$:

$$\Lambda = A_k = R_{k-1}^TR_{k-2}^T\text{...}R_0^TAR_0\text{...}R_{k-2}R_{k-1}$$
$$\Lambda = V^T A V$$
with $V = R_0R_1\text{...}R_{k-1}$

### Givens step

$$A' = R^T A R$$

The goal is to insert a 0 into $A'_{ij}$ and $A'_{ji}$.  
$A_{ij}$ is selected at each step as the element wih highest manitude below (or above) the diagonal.  
$R$ is a givens matrix $G(i, j, c, s)$.
Results of one step:

- $a'_{ij} = a'_{ji} = (c^2 - s^2) a_{ij} + cs(a_{ii} - a_{jj})$
- $a'_{ii} = c^2a_{ii} + s^2a_{jj} - 2csa_{ij}$
- $a'_{jj} = c^2a_{jj} + s^2a_{ii} + 2csa_{ij}$
- $a'_{ik} = a'_{ki} = ca_{ik} - sa_{jk} \space (k \neq i, k \neq j)$
- $a'_{jk} = a'_{kj} = ca_{jk} + sa_{ik} \space (k \neq i, k \neq j)$
- $a'_{kl} = a_{kl} \space (k \neq i, l \neq j)$  


$c$ and $s$ are chosen by solving the equation
$$a'_{ij} = 0$$

Let $w = \frac{a_{jj} - a_{ii}}{2a_{ij}}$ and $t = \frac{s}{c}$

$t = -w \pm \sqrt{w^2 + 1}$

We choose the $t$ with the smaller absolute value:

$$
t = 
\begin{cases}
    -w + \sqrt{w^2 + 1} & \text{if } w \geq 0\\
    -w - \sqrt{w^2 + 1} & \text{if } w < 0
\end{cases}
$$

$$c = \frac{1}{\sqrt{1+t^2}}$$
$$s = \frac{t}{\sqrt{1+t^2}}$$

### Convergence

It converges to a diagonal matrix with a variable number of steps.  
The algorithm should be stopped when the diagonal elements of $A_k$ stops moving


### Rearrange eigenvalues and eigenvectors

The diagonal of $A_k$ contains the eigenvalues, and $V_k = R_0R_1\text{...}R_{k-1}$ the eigenvectors.  
The eigenvalues should be sorted by increasing order, and rearrange $V_k$ at the same time.

In [173]:
def given_mat(n, i, j, c, s):
    G = np.eye(n)
    G[i, i] = c
    G[j, j] = c
    G[i, j] = s
    G[j, i] = -s
    return G

def sort_eigs(d, P):
    dl = d.tolist()
    pl = list()
    for i in range(len(d)):
        pl.append(P[:, i])
    
    dl, pl = zip(*sorted(zip(dl, pl)))
    
    d = np.array(dl)
    P = np.array(pl).T
    
    return d, P
    

def eig_jacobi_naive(A):
    n = len(A)
    Ak = A.copy()
    Vk = np.eye(n)
    
    iters = 0
    while True:
        #Find position of sub-diagonal element with highest abs val
        Apr = np.abs(Ak - np.triu(Ak)).ravel()
        id0 = np.argmax(Apr)
        i0 = int(id0 / n)
        j0 = int(id0 % n)

        #compute c, s that will put 0 on A[i0,j0] and A[j0,i0]
        w = (Ak[j0,j0] - Ak[i0, i0]) / (2 * Ak[i0, j0])
        if w > 0:
            t = - w + np.sqrt(w*w + 1)
        else:
            t = - w - np.sqrt(w*w + 1)
        c = 1 / np.sqrt(1 + t*t)
        s = t / np.sqrt(1 + t*t)

        #Update Ak and Vk
        oldd = np.diag(Ak)
        R = given_mat(n, i0, j0, c, s)
        Ak = R.T @ Ak @ R
        Vk = Vk @ R
        iters += 1
        
        #Stop if diagonal almost didn't change
        newd = np.diag(Ak)
        update_dist = np.linalg.norm(oldd - newd)
        if update_dist < 1e-16:
            break
        
    #print('niters:', iters)
    d, P = sort_eigs(np.diag(Ak), Vk)
    return d, P

A = np.random.randn(5, 5)
A = A.T @ A
d, P = eig_jacobi_naive(A)

for i in range(len(d)):
    print(metrics.tdist(A @ P[:, i], d[i] * P[:, i]))

print(metrics.tdist(np.linalg.inv(P) @ A @ P, np.diag(d)))
print(metrics.tdist(P @ np.diag(d) @ np.linalg.inv(P), A))

4.2250370943933804e-10
1.4938479235475212e-09
8.89446656241921e-09
8.846990144146125e-09
1.1817270681122074e-09
1.2695957653421157e-08
1.2695957634361838e-08


### Inplace algorithm

Instead of computing R and doing the matrix multiplication to update $A$ and $V$, it's possible to update them directly inplace, at a cost of $O(n)$.

### Update of A

$$A' = R^T A R$$

- $a'_{ii} = a_{ii} - ta_{ij}$
- $a'_{jj} = a_{jj} + ta_{ij}$
- $a'_{ik} = a'_{ki} = ca_{ik} - sa_{jk} \space (k \neq i, k \neq j)$
- $a'_{jk} = a'_{kj} = ca_{jk} + sa_{ik} \space (k \neq i, k \neq j)$
- $a'_{kl} = a_{kl} \space (k \neq i, l \neq j)$

Because $A$ is symmetric, it's possible to never read / write the lower or the upper half of $A$.

### Update of V

$$V' = V R$$

- $v'_{ki} = c v_{ki} - s v_{kj}$
- $v'_{kj} = c v_{kj} + s v_{ki}$
- $v'_{kl} = v_{kl} \space (l \neq i, l \neq j)$

In [246]:
def sort_eigs(d, P):
    dl = d.tolist()
    pl = list()
    for i in range(len(d)):
        pl.append(P[:, i])
    
    dl, pl = zip(*sorted(zip(dl, pl)))
    
    d = np.array(dl)
    P = np.array(pl).T
    
    return d, P

def update_a(A, i, j, c, s, t):
    A[i,i] = A[i,i] - t * A[i,j]
    A[j,j] = A[j,j] + t * A[i,j]
    
    for k in range(len(A)):
        aik = A[max(i,k), min(i,k)]
        ajk = A[max(j,k), min(j,k)]
        
        if i != k:
            A[max(i,k), min(i,k)] = c * aik - s * ajk
        if j != k:
            A[max(j,k), min(j,k)] = c * ajk + s * aik
    
    A[i,j] = 0
    
def update_AR(A, i, j, c, s):
    for k in range(len(A)):
        aki = A[k,i]
        akj = A[k,j]
        A[k,i] = c * aki - s * akj
        A[k,j] = c * akj + s * aki
        
    

def eig_jacobi(A):
    n = len(A)
    Ak = A.copy()
    Vk = np.eye(n)
    
    iters = 0
    while True:
        #Find position of sub-diagonal element with highest abs val
        Apr = np.abs(Ak - np.triu(Ak)).ravel()
        id0 = np.argmax(Apr)
        i0 = int(id0 / n)
        j0 = int(id0 % n)

        #compute c, s that will put 0 on A[i0,j0] and A[j0,i0]
        w = (Ak[j0,j0] - Ak[i0, i0]) / (2 * Ak[i0, j0])
        if w > 0:
            t = - w + np.sqrt(w*w + 1)
        else:
            t = - w - np.sqrt(w*w + 1)
        c = 1 / np.sqrt(1 + t*t)
        s = t / np.sqrt(1 + t*t)

        #Update Ak and Vk
        oldd = np.diag(Ak).copy()
        update_a(Ak, i0, j0, c, s, t)
        update_AR(Vk, i0, j0, c, s)
        iters += 1
        
        #Stop if diagonal almost didn't change
        newd = np.diag(Ak)
        update_dist = np.linalg.norm(oldd - newd)
        if update_dist < 1e-16:
            break
        
    #print('niters:', iters) 
    d, P = sort_eigs(np.diag(Ak), Vk)
    return d, P


A = np.random.randn(5, 5)
A = A.T @ A
d, P = eig_jacobi(A)

for i in range(len(d)):
    print(metrics.tdist(A @ P[:, i], d[i] * P[:, i]))
print(metrics.tdist(np.linalg.inv(P) @ A @ P, np.diag(d)))
print(metrics.tdist(P @ np.diag(d) @ np.linalg.inv(P), A))

2.0912088467606657e-08
5.344233377320964e-09
4.292291553945011e-09
2.0958534765030162e-08
3.0097659458076427e-09
3.0538810614493146e-08
3.053881000947833e-08
