In [24]:
import sys
sys.path.append('..')

import numpy as np

import metrics

# Matrix similarity

Let $A$ and $B$ matrices of size $n*n$.  
$A$ and $B$ are similar if it exists an invertible matrix $P \in \mathbb{R}^{n*n}$ such that:
$$B = P^{-1}AP$$  

# Diagonalization

Let $A \in \mathbb{R}^{n*n}$
A is diagonalizable if it similar to a diagonal matrix.  
IE there is an invertible matrix $P \in \mathbb{R}^{n*n}$ such that $P^{-1}AP$ is diagonal.

The diagonilazation of matrix $A$ is:
$$P^{-1} A P = D$$
with $P \in \mathbb{R}^{n*n}$ is a matrix whose columns are the right eigenvectors of $A$.  
And $D \in \mathbb{R}^{n*n}$ a digonal matrix whose entries $D_{ii}$ is the eigeinvalue of $A$ corresponding to the eigeinvector $P_i$.  

The equation can be rewritten as:

$$A = PDP^{-1}$$

In [55]:
A = np.array([
    [1, 2, 1],
    [6, -1, 0],
    [-1, 2, 1]
])
d, P = np.linalg.eig(A)

print('A =\n', A)
print('P = \n', P)
print('diag(D)=\n', d)


D2 = np.linalg.inv(P) @ A @ P
print('P^-1AP=\n', D2)
print(metrics.tdist(np.diag(d), D2))

A2 = P @ np.diag(d) @ np.linalg.inv(P)
print('PDP^-1=\n', A2)
print(metrics.tdist(A, A2))

A =
 [[ 1  2  1]
 [ 6 -1  0]
 [-1  2  1]]
P = 
 [[ 0.60588985  0.28934634 -0.08122258]
 [ 0.73792101 -0.83016763 -0.41839386]
 [ 0.29727105  0.47655053  0.9046267 ]]
diag(D)=
 [ 3.92646107 -3.09123795  0.16477688]
P^-1AP=
 [[ 3.92646107e+00 -8.47397419e-16  5.54699765e-16]
 [ 3.69366844e-15 -3.09123795e+00  7.06300920e-16]
 [ 7.25290929e-16  3.97623940e-18  1.64776876e-01]]
4.431847301282925e-15
PDP^-1=
 [[ 1.00000000e+00  2.00000000e+00  1.00000000e+00]
 [ 6.00000000e+00 -1.00000000e+00  9.30119432e-16]
 [-1.00000000e+00  2.00000000e+00  1.00000000e+00]]
6.604835229600313e-15


# Square root of a matrix

Let $A$ and $B$ matrices of size $n*n$.  
Matrix $B$ is the square root of $A$ is $BB = A$  
The square root is denoted $B = A^{\frac{1}{2}}$  

A matrix may have several or no square root

If $A$ is diagonal, $B$ is a diagonal matrix whose entries are the square root of the diagonal entries of $A$

In [43]:
A = np.diag(np.random.randn(5)**2)
B = np.diag(np.sqrt(np.diag(A)))
print(metrics.tdist(A, B @ B))

0.0


If $A$ is diagonalizable with positive eigenvalues, the square root of $A$ is:

$$B = PD^{\frac{1}{2}}P^{-1}$$

In [59]:
A = np.array([
    [2, -2, 1],
    [-1, 3, -1],
    [2, -4, 3]
])
d, P = np.linalg.eig(A)

s = np.sqrt(d)
B = P @ np.diag(s) @ np.linalg.inv(P)
print(B)
print(metrics.tdist(B @ B, A))

[[ 1.28989795 -0.5797959   0.28989795]
 [-0.28989795  1.5797959  -0.28989795]
 [ 0.5797959  -1.15959179  1.5797959 ]]
1.900395703982448e-15


## Square root Inverse

$$A^{-\frac{1}{2}} = \text{inv}(A^{\frac{1}{2}})$$

$A^{-\frac{1}{2}}$ is the square root of $A^{-1}$:
$$A^{-\frac{1}{2}}A^{-\frac{1}{2}} = A^{-1}$$

If $A$ is diagonal, $A^{-\frac{1}{2}}$ is a diagonal matrix whose entries are the inverse square root of the diagonal entries of $A$

In [94]:
A = np.diag(3.8 * np.random.randn(5)**2 + 1.2)
B = np.diag(1 / np.sqrt(np.diag(A)))
print(metrics.tdist(np.linalg.inv(A), B @ B))

6.509259464525837e-17


If $A$ is diagonalizable with positive eigenvalues, the inverse square root of $A$ is:

$$A^{-\frac{1}{2}} = PD^{-\frac{1}{2}}P^{-1}$$

In [93]:
A = np.array([
    [2, -2, 1],
    [-1, 3, -1],
    [2, -4, 3]
])
d, P = np.linalg.eig(A)

s = 1 / np.sqrt(d)
B = P @ np.diag(s) @ np.linalg.inv(P) 
print(B)
print(metrics.tdist(B @ B, np.linalg.inv(A)))

[[ 0.88164966  0.23670068 -0.11835034]
 [ 0.11835034  0.76329932  0.11835034]
 [-0.23670068  0.47340137  0.76329932]]
1.1025638216888958e-15


# Symmetric positive definite

Let $A$ a symmetric positive definite matrix. A is always diagonalizable:

$$P^T A P = D$$

With $P$, the marix of eigeinvectors, is an orthogonal matrix ($PP^T=P^TP=I$).

In [102]:
A = np.random.randn(4, 4)
A = A.T @ A
d, P = np.linalg.eigh(A)

print('A =\n', A)
print('P = \n', P)
print('diag(D)=\n', d)


D2 = np.linalg.inv(P) @ A @ P
print('P^-1AP=\n', D2)
print(metrics.tdist(np.diag(d), D2))

A2 = P @ np.diag(d) @ np.linalg.inv(P)
print('PDP^-1=\n', A2)
print(metrics.tdist(A, A2))

print(metrics.tdist(P @ P.T, np.eye(4)))
print(metrics.tdist(P.T @ P, np.eye(4)))

A =
 [[ 1.52098065 -1.84427989  0.90801682 -0.71696289]
 [-1.84427989  7.59521016 -0.31302098 -1.3882128 ]
 [ 0.90801682 -0.31302098  1.95122817  1.05190951]
 [-0.71696289 -1.3882128   1.05190951  4.02915553]]
P = 
 [[ 0.7545719   0.53480767 -0.30200481  0.2310738 ]
 [ 0.22649461  0.20718112  0.22529854 -0.92467115]
 [-0.50863947  0.81205905  0.25943819  0.12057286]
 [ 0.34728565 -0.10778147  0.88922747  0.27757943]]
diag(D)=
 [0.0253464  2.32975479 4.22783296 8.51364036]
P^-1AP=
 [[ 2.53464004e-02 -1.23632412e-16  1.25744010e-16  1.06867316e-15]
 [ 1.58503135e-17  2.32975479e+00  4.18536755e-17 -8.33132788e-16]
 [ 1.17855422e-16 -3.46490686e-16  4.22783296e+00  3.51973990e-16]
 [ 3.24306228e-17  9.32785919e-16 -1.30992096e-16  8.51364036e+00]]
2.0013445025964555e-15
PDP^-1=
 [[ 1.52098065 -1.84427989  0.90801682 -0.71696289]
 [-1.84427989  7.59521016 -0.31302098 -1.3882128 ]
 [ 0.90801682 -0.31302098  1.95122817  1.05190951]
 [-0.71696289 -1.3882128   1.05190951  4.02915553]]
2.823984

# Computing: Diagonalization of Non-Symetric matrix

## Implicitly-Shifted QR

The Implicitly-shifted QR algorithm is a method to compute the eigenvalues and eigenvectors of any square matrix

## Naive diagonalization

### Explicit QR algorithm: Find eigenvalues

- Let $A_0 = A$
- Iterate:
    - Compute the $QR$ factorization of $A$: $A_k = Q_k R_k$
    - Let $A_{k+1} = Q_k R_k$

As $k \to \infty$, $A_k$ converges to the Schur form of $A$, an upper-triangular matrix.
$$A_{k+1} = Q_k^{-1}A_kQ_k$$
So $A$, $A_1$, ..., $A_k$ are all similar, and thus they share the same eigenvalues.  
The eigenvalues of the upper-triangular matrix $A_k$ lie on the diagionals, they are the eigenvalues of $A$

In [109]:
def qr_algorithm(A, max_iters=1000):
    
    Ak = A.copy()
    for k in range(max_iters):
        # Compute norm below diagonal
        lnorm = np.linalg.norm(Ak - np.triu(Ak))
        if lnorm < 1e-10: break
        
        Q, R = np.linalg.qr(Ak)
        Ak = R @ Q
    
    return np.diag(Ak)

A = np.array([
    [2, -2, 1],
    [-1, 3, -1],
    [2, -4, 3]
])

d = qr_algorithm(A)
d2, _ = np.linalg.eig(A)

print(d)
print(d2)
print(metrics.tdist(d, d2))

[6. 1. 1.]
[6. 1. 1.]
6.3873580624876566e-12


### Compute the eigenvectors from a corresponding eigenvalue

$$Av = \lambda v$$
$$(A - \lambda I)v = \vec{0}$$

An orthogonal basis of $\text{Null}(A - \lambda I)$ is a set of eigenvectors for the eigeinvalue $\lambda$

In [150]:
def sv_rank(s):
    i = 0
    while i < len(s):
        if s[i] * s[i] < 1e-12:
            break
        i += 1
    return i

def find_evec(A, d):
    amd = A - np.eye(len(A)) * d
    U, s, VT = np.linalg.svd(amd)
    r = sv_rank(s)
    return VT[r:].T

def my_eig(A):
    d = qr_algorithm(A)
    vects = None
    for i in range(len(d)):
        if i > 0 and (d[i] - d[i-1])**2 < 1e-12:
            continue
        
        v = find_evec(A, d[i])
        if vects is None:
            vects = v
        else:
            vects = np.concatenate((vects, v), axis = 1)
    return d, vects
    
    
A = np.array([
    [2, -2, 1],
    [-1, 3, -1],
    [2, -4, 3]
])

d, P = my_eig(A)
d2, P2 = np.linalg.eig(A)

for i in range(len(d)):
    print(metrics.tdist(A @ P[:, i], d[i] * P[:, i]))

print(metrics.tdist(np.linalg.inv(P) @ A @ P, np.diag(d)))
print(metrics.tdist(P @ np.diag(d) @ np.linalg.inv(P), A))

1.4812106129721512e-12
3.3603528951155397e-12
6.352821333422274e-12
6.725357375506194e-12
8.730925457289283e-12


# Computing: Diagonalization of Symetric matrix

## Jacobi Eigenvalue algorithm

The Jacobi eigenvalue algorithm is an iterative method to compute the eigenvalues and eigenvectors of a real symmetric matrix