In [1]:
import sys
sys.path.append('..')

import numpy as np

import metrics

# Matrix similarity

Let $A$ and $B$ matrices of size $n*n$.  
$A$ and $B$ are similar if it exists an invertible matrix $P \in \mathbb{R}^{n*n}$ such that:
$$B = P^{-1}AP$$  

# Diagonalization

Let $A \in \mathbb{R}^{n*n}$
A is diagonalizable if it similar to a diagonal matrix.  
IE there is an invertible matrix $P \in \mathbb{R}^{n*n}$ such that $P^{-1}AP$ is diagonal.

The diagonilazation of matrix $A$ is:
$$P^{-1} A P = D$$
with $P \in \mathbb{R}^{n*n}$ is a matrix whose columns are the right eigenvectors of $A$.  
And $D \in \mathbb{R}^{n*n}$ a digonal matrix whose entries $D_{ii}$ is the eigeinvalue of $A$ corresponding to the eigeinvector $P_i$.  

The equation can be rewritten as:

$$A = PDP^{-1}$$

In [2]:
A = np.array([
    [1, 2, 1],
    [6, -1, 0],
    [-1, 2, 1]
])
d, P = np.linalg.eig(A)

print('A =\n', A)
print('P = \n', P)
print('diag(D)=\n', d)


D2 = np.linalg.inv(P) @ A @ P
print('P^-1AP=\n', D2)
print(metrics.tdist(np.diag(d), D2))

A2 = P @ np.diag(d) @ np.linalg.inv(P)
print('PDP^-1=\n', A2)
print(metrics.tdist(A, A2))

A =
 [[ 1  2  1]
 [ 6 -1  0]
 [-1  2  1]]
P = 
 [[ 0.60588985  0.28934634 -0.08122258]
 [ 0.73792101 -0.83016763 -0.41839386]
 [ 0.29727105  0.47655053  0.9046267 ]]
diag(D)=
 [ 3.92646107 -3.09123795  0.16477688]
P^-1AP=
 [[ 3.92646107e+00 -8.47397419e-16  5.54699765e-16]
 [ 3.69366844e-15 -3.09123795e+00  7.06300920e-16]
 [ 7.25290929e-16  3.97623940e-18  1.64776876e-01]]
4.431847301282925e-15
PDP^-1=
 [[ 1.00000000e+00  2.00000000e+00  1.00000000e+00]
 [ 6.00000000e+00 -1.00000000e+00  9.30119432e-16]
 [-1.00000000e+00  2.00000000e+00  1.00000000e+00]]
6.604835229600313e-15


# Square root of a matrix

Let $A$ and $B$ matrices of size $n*n$.  
Matrix $B$ is the square root of $A$ is $BB = A$  
The square root is denoted $B = A^{\frac{1}{2}}$  

A matrix may have several or no square root

If $A$ is diagonal, $B$ is a diagonal matrix whose entries are the square root of the diagonal entries of $A$

In [3]:
A = np.diag(np.random.randn(5)**2)
B = np.diag(np.sqrt(np.diag(A)))
print(metrics.tdist(A, B @ B))

0.0


If $A$ is diagonalizable with positive eigenvalues, the square root of $A$ is:

$$B = PD^{\frac{1}{2}}P^{-1}$$

In [4]:
A = np.array([
    [2, -2, 1],
    [-1, 3, -1],
    [2, -4, 3]
])
d, P = np.linalg.eig(A)

s = np.sqrt(d)
B = P @ np.diag(s) @ np.linalg.inv(P)
print(B)
print(metrics.tdist(B @ B, A))

[[ 1.28989795 -0.5797959   0.28989795]
 [-0.28989795  1.5797959  -0.28989795]
 [ 0.5797959  -1.15959179  1.5797959 ]]
1.900395703982448e-15


## Square root Inverse

$$A^{-\frac{1}{2}} = \text{inv}(A^{\frac{1}{2}})$$

$A^{-\frac{1}{2}}$ is the square root of $A^{-1}$:
$$A^{-\frac{1}{2}}A^{-\frac{1}{2}} = A^{-1}$$

If $A$ is diagonal, $A^{-\frac{1}{2}}$ is a diagonal matrix whose entries are the inverse square root of the diagonal entries of $A$

In [5]:
A = np.diag(3.8 * np.random.randn(5)**2 + 1.2)
B = np.diag(1 / np.sqrt(np.diag(A)))
print(metrics.tdist(np.linalg.inv(A), B @ B))

1.576213700060856e-16


If $A$ is diagonalizable with positive eigenvalues, the inverse square root of $A$ is:

$$A^{-\frac{1}{2}} = PD^{-\frac{1}{2}}P^{-1}$$

In [6]:
A = np.array([
    [2, -2, 1],
    [-1, 3, -1],
    [2, -4, 3]
])
d, P = np.linalg.eig(A)

s = 1 / np.sqrt(d)
B = P @ np.diag(s) @ np.linalg.inv(P) 
print(B)
print(metrics.tdist(B @ B, np.linalg.inv(A)))

[[ 0.88164966  0.23670068 -0.11835034]
 [ 0.11835034  0.76329932  0.11835034]
 [-0.23670068  0.47340137  0.76329932]]
1.1025638216888958e-15


# Symmetric positive definite

Let $A$ a symmetric positive definite matrix. A is always diagonalizable:

$$P^T A P = D$$

With $P$, the marix of eigeinvectors, is an orthogonal matrix ($PP^T=P^TP=I$).

In [7]:
A = np.random.randn(4, 4)
A = A.T @ A
d, P = np.linalg.eigh(A)

print('A =\n', A)
print('P = \n', P)
print('diag(D)=\n', d)


D2 = np.linalg.inv(P) @ A @ P
print('P^-1AP=\n', D2)
print(metrics.tdist(np.diag(d), D2))

A2 = P @ np.diag(d) @ np.linalg.inv(P)
print('PDP^-1=\n', A2)
print(metrics.tdist(A, A2))

print(metrics.tdist(P @ P.T, np.eye(4)))
print(metrics.tdist(P.T @ P, np.eye(4)))

A =
 [[ 6.23331003  4.33372988  2.76569545 -0.28014379]
 [ 4.33372988  9.65064034  3.08689761  1.15246176]
 [ 2.76569545  3.08689761  2.09617771 -1.07783192]
 [-0.28014379  1.15246176 -1.07783192  4.62011764]]
P = 
 [[-0.25213979  0.73708197  0.3137088  -0.54288349]
 [-0.21433429 -0.5216396  -0.28677963 -0.7744097 ]
 [ 0.90553983 -0.0435519   0.27253789 -0.32221723]
 [ 0.26548814  0.42744066 -0.86317283 -0.04175155]]
diag(D)=
 [ 0.27944761  2.84041564  5.44513915 14.03524331]
P^-1AP=
 [[ 2.79447606e-01 -3.17466972e-16 -4.65132399e-16 -1.30819599e-15]
 [-3.05849448e-16  2.84041564e+00  7.00141407e-16  3.30928084e-16]
 [-1.51948090e-16  6.11055322e-16  5.44513915e+00  4.02179789e-16]
 [-7.56508316e-16  1.36208461e-15  5.01746353e-16  1.40352433e+01]]
4.469219908328811e-15
PDP^-1=
 [[ 6.23331003  4.33372988  2.76569545 -0.28014379]
 [ 4.33372988  9.65064034  3.08689761  1.15246176]
 [ 2.76569545  3.08689761  2.09617771 -1.07783192]
 [-0.28014379  1.15246176 -1.07783192  4.62011764]]
5.935

# Computing: Diagonalization of Non-Symetric matrix

## Implicitly-Shifted QR

The Implicitly-shifted QR algorithm is a method to compute the eigenvalues and eigenvectors of any square matrix.  
It can only be applied to upper hessenberg matrices. The algorithm is in 3 steps:
- Convert $A$ to an upper hessenberg form
- Diagonalize the special matrix
- Get the diagonalization of $A$ from the previous step

### Convert a matrix to upper Hessenberg Form

A matrix in upper Hessenberg form is almost upper triangular, all entries below the first subdiagonal are zeroes:

$$
\begin{bmatrix}
   * & * & * & * & * \\
   * & * & * & * & * \\
   0 & * & * & * & * \\
   0 & 0 & * & * & * \\
   0 & 0 & 0 & * & *
\end{bmatrix}
$$

Let $A \in \mathbb{R}^{n*n}$, it can be brought to upper hessenberg form, it's decomposition is:

$$B = P A P^T$$

with $B \in \mathbb{R}^{n*n}$ matrix in upper hessenberg form, and $P \in \mathbb{R}^{n*n}$ orthogonal matrix.

Using a householder transformation, we can insert zeros below the diagonal with a matrix $P_1$. But multiplying by $P_1^T$ will reinsert values below the diagonal.  
But if $P_1$ Only insert zeros below the subdiagonal, multypling by $P_1^T$ will not affect the first column, and the zeros will remain:

$$
\begin{gather}
 P_1 A P_1^T=
\begin{bmatrix}
   * & * & * & * & * \\
   * & * & * & * & * \\
   0 & * & * & * & * \\
   0 & * & * & * & * \\
   0 & * & * & * & *
   \end{bmatrix}
\end{gather}
$$

With $n - 2$ transformations, it's possible to insert zeros below all the subdiagonal of $A$.

$$P_{n-2}P_{n-3}\text{...}P_2P_1AP_1^TP_2^T\text{...}P_{n-3}^TP_{n-2}^T = B$$

$$P = P_{n-2}P_{n-3}\text{...}P_2P_1$$

In [34]:
def house_vect(x):
    v = x.copy()
    v[0] = x[0] + np.sign(x[0]) * np.linalg.norm(x)
    return v
    
def house_mat(v):
    return np.eye(len(v)) - 2 * np.outer(v, v) / (v@v)


def hessen(A):
    n = len(A)
    Ak = A.copy()
    Q = np.eye(n)
    
    for j in range(n-2):
    
        v = house_vect(Ak[j+1:, j])
        P = np.eye(n)
        P[j+1:, j+1:] = house_mat(v)
        Q = P @ Q
        Ak = P @ Ak @ P.T
    
    return Ak, Q
    
    
A = np.random.randn(5, 5)
A2, P = hessen(A)

print(A2)

print(metrics.tdist(P @ P.T, np.eye(len(P))))
print(metrics.tdist(P.T @ P, np.eye(len(P))))
print(metrics.tdist(P @ A @ P.T, A2))
print(metrics.tdist(P.T @ A2 @ P, A))

[[-1.40842694e+00 -6.13025075e-01 -1.25193962e+00  4.36522077e-02 -5.43925952e-01]
 [-1.50196259e+00 -5.58273025e-02 -1.79887235e-01  6.09479763e-01  8.22192510e-01]
 [ 1.16693404e-16 -1.33006578e+00  3.86081672e-01  8.34078754e-01 -1.22338515e+00]
 [-1.20764315e-16 -2.11989335e-16 -1.01745407e+00 -9.94534539e-01 -1.20259067e-01]
 [-9.70371719e-17  1.19772764e-16 -5.68680525e-17 -1.37186034e+00 -4.25727660e-01]]
5.82136858187381e-16
5.492663168473741e-16
5.447380579253156e-16
1.4856891323812508e-15


### Diagonalize an upper hessenberg matrix

In [92]:
X = np.random.randn(5, 5)
A, _ = hessen(X)

print(A)

[[-4.94742064e-01  2.41893300e+00 -4.21132297e-01 -1.58079363e+00 -3.70523833e-01]
 [-7.12394584e-01  4.13038321e-01 -5.26567374e-01 -1.21027219e+00 -1.03747174e+00]
 [ 3.98501344e-18 -2.93885670e+00 -7.71085382e-01  3.34826889e-03  1.25781760e-01]
 [ 7.05373816e-18 -1.90979144e-16  1.55750471e+00  2.46365921e+00  3.88102484e-01]
 [ 9.27359231e-17 -8.21832036e-17 -1.16957658e-16 -8.11081530e-02  2.10565083e+00]]


### Get the diagonalization of A

Let $A \in \mathbb{R}^{n*n}$.  
Let $B \in \mathbb{R}^{n*n}$ upper hessenberg matrix:
$$B = QAQ^T$$
The diagonalization of $B$ is:
$$B = P_BD_BP_B^{-1}$$

$A$ and $B$ are similar, they have the same eigenvalues.

$$A = Q^TBQ = Q^TP_BD_BP_B^{-1}Q$$

The diagonalization of $A$ is:
$$A = PDP^{-1}$$
with $D = D_B$ and $P = Q^T P_B$

In [96]:
def my_eig(A):
    B, Q = hessen(A)
    db, Pb = np.linalg.eig(B)
    d = db
    P = Q.T @ Pb
    return d, P

X1 = np.random.randn(5, 5)
X2 = np.diag(np.random.randn(len(X1)))
A = X1 @ X2 @ np.linalg.inv(X1)
d, P = my_eig(A)

for i in range(len(d)):
    print(metrics.tdist(A @ P[:, i], d[i] * P[:, i]))

print(metrics.tdist(np.linalg.inv(P) @ A @ P, np.diag(d)))
print(metrics.tdist(P @ np.diag(d) @ np.linalg.inv(P), A))

1.817513422402428e-15
1.3574718305694992e-15
6.648115616385374e-15
4.535834518494392e-15
4.1755309363659096e-15
1.564265705725026e-14
4.055954848369357e-14


## Naive diagonalization

### Explicit QR algorithm: Find eigenvalues

- Let $A_0 = A$
- Iterate:
    - Compute the $QR$ factorization of $A$: $A_k = Q_k R_k$
    - Let $A_{k+1} = Q_k R_k$

As $k \to \infty$, $A_k$ converges to the Schur form of $A$, an upper-triangular matrix.
$$A_{k+1} = Q_k^{-1}A_kQ_k$$
So $A$, $A_1$, ..., $A_k$ are all similar, and thus they share the same eigenvalues.  
The eigenvalues of the upper-triangular matrix $A_k$ lie on the diagionals, they are the eigenvalues of $A$

In [8]:
def qr_algorithm(A, max_iters=1000):
    
    Ak = A.copy()
    for k in range(max_iters):
        # Compute norm below diagonal
        lnorm = np.linalg.norm(Ak - np.triu(Ak))
        if lnorm < 1e-10: break
        
        Q, R = np.linalg.qr(Ak)
        Ak = R @ Q
    
    return np.diag(Ak)

A = np.array([
    [2, -2, 1],
    [-1, 3, -1],
    [2, -4, 3]
])

d = qr_algorithm(A)
d2, _ = np.linalg.eig(A)

print(d)
print(d2)
print(metrics.tdist(d, d2))

[6. 1. 1.]
[6. 1. 1.]
6.3873580624876566e-12


### Compute the eigenvectors from a corresponding eigenvalue

$$Av = \lambda v$$
$$(A - \lambda I)v = \vec{0}$$

An orthogonal basis of $\text{Null}(A - \lambda I)$ is a set of eigenvectors for the eigeinvalue $\lambda$

In [9]:
def sv_rank(s):
    i = 0
    while i < len(s):
        if s[i] * s[i] < 1e-12:
            break
        i += 1
    return i

def find_evec(A, d):
    amd = A - np.eye(len(A)) * d
    U, s, VT = np.linalg.svd(amd)
    r = sv_rank(s)
    return VT[r:].T

def my_eig(A):
    d = qr_algorithm(A)
    vects = None
    for i in range(len(d)):
        if i > 0 and (d[i] - d[i-1])**2 < 1e-12:
            continue
        
        v = find_evec(A, d[i])
        if vects is None:
            vects = v
        else:
            vects = np.concatenate((vects, v), axis = 1)
    return d, vects
    
    
A = np.array([
    [2, -2, 1],
    [-1, 3, -1],
    [2, -4, 3]
])
d, P = my_eig(A)

for i in range(len(d)):
    print(metrics.tdist(A @ P[:, i], d[i] * P[:, i]))

print(metrics.tdist(np.linalg.inv(P) @ A @ P, np.diag(d)))
print(metrics.tdist(P @ np.diag(d) @ np.linalg.inv(P), A))

1.4812106129721512e-12
3.3603528951155397e-12
6.352821333422274e-12
6.725357375506194e-12
8.730925457289283e-12


# Computing: Diagonalization of Symetric matrix

## Jacobi Eigenvalue algorithm

The Jacobi eigenvalue algorithm is an iterative method to compute the eigenvalues and eigenvectors of a real symmetric matrix

### General algorithm

Let $A \in \mathbb{R}^{n*n}$ symmetric matrix

Let $A_0 = A$

$$A_{k+1} = R_k^T A_k R_k$$

with $R_k \in \mathbb{R}^{n*n}$ a givens rotation matrix.

All $A_k$ are symmetric with $A_k \to \Lambda$ as $k \to \infty$  

The algorithm converges to the diagonalization of $A$:

$$\Lambda = A_k = R_{k-1}^TR_{k-2}^T\text{...}R_0^TAR_0\text{...}R_{k-2}R_{k-1}$$
$$\Lambda = V^T A V$$
with $V = R_0R_1\text{...}R_{k-1}$

### Givens step

$$A' = R^T A R$$

The goal is to insert a 0 into $A'_{ij}$ and $A'_{ji}$.  
$A_{ij}$ is selected at each step as the element wih highest manitude below (or above) the diagonal.  
$R$ is a givens matrix $G(i, j, c, s)$.
Results of one step:

- $a'_{ij} = a'_{ji} = (c^2 - s^2) a_{ij} + cs(a_{ii} - a_{jj})$
- $a'_{ii} = c^2a_{ii} + s^2a_{jj} - 2csa_{ij}$
- $a'_{jj} = c^2a_{jj} + s^2a_{ii} + 2csa_{ij}$
- $a'_{ik} = a'_{ki} = ca_{ik} - sa_{jk} \space (k \neq i, k \neq j)$
- $a'_{jk} = a'_{kj} = ca_{jk} + sa_{ik} \space (k \neq i, k \neq j)$
- $a'_{kl} = a_{kl} \space (k \neq i, l \neq j)$  


$c$ and $s$ are chosen by solving the equation
$$a'_{ij} = 0$$

Let $w = \frac{a_{jj} - a_{ii}}{2a_{ij}}$ and $t = \frac{s}{c}$

$t = -w \pm \sqrt{w^2 + 1}$

We choose the $t$ with the smaller absolute value:

$$
t = 
\begin{cases}
    -w + \sqrt{w^2 + 1} & \text{if } w \geq 0\\
    -w - \sqrt{w^2 + 1} & \text{if } w < 0
\end{cases}
$$

$$c = \frac{1}{\sqrt{1+t^2}}$$
$$s = \frac{t}{\sqrt{1+t^2}}$$

### Convergence

It converges to a diagonal matrix with a variable number of steps.  
The algorithm should be stopped when the diagonal elements of $A_k$ stops moving


### Rearrange eigenvalues and eigenvectors

The diagonal of $A_k$ contains the eigenvalues, and $V_k = R_0R_1\text{...}R_{k-1}$ the eigenvectors.  
The eigenvalues should be sorted by increasing order, and rearrange $V_k$ at the same time.

In [10]:
def given_mat(n, i, j, c, s):
    G = np.eye(n)
    G[i, i] = c
    G[j, j] = c
    G[i, j] = s
    G[j, i] = -s
    return G

def sort_eigs(d, P):
    dl = d.tolist()
    pl = list()
    for i in range(len(d)):
        pl.append(P[:, i])
    
    dl, pl = zip(*sorted(zip(dl, pl)))
    
    d = np.array(dl)
    P = np.array(pl).T
    
    return d, P
    

def eig_jacobi_naive(A):
    n = len(A)
    Ak = A.copy()
    Vk = np.eye(n)
    
    iters = 0
    while True:
        #Find position of sub-diagonal element with highest abs val
        Apr = np.abs(Ak - np.triu(Ak)).ravel()
        id0 = np.argmax(Apr)
        i0 = int(id0 / n)
        j0 = int(id0 % n)

        #compute c, s that will put 0 on A[i0,j0] and A[j0,i0]
        w = (Ak[j0,j0] - Ak[i0, i0]) / (2 * Ak[i0, j0])
        if w > 0:
            t = - w + np.sqrt(w*w + 1)
        else:
            t = - w - np.sqrt(w*w + 1)
        c = 1 / np.sqrt(1 + t*t)
        s = t / np.sqrt(1 + t*t)

        #Update Ak and Vk
        oldd = np.diag(Ak)
        R = given_mat(n, i0, j0, c, s)
        Ak = R.T @ Ak @ R
        Vk = Vk @ R
        iters += 1
        
        #Stop if diagonal almost didn't change
        newd = np.diag(Ak)
        update_dist = np.linalg.norm(oldd - newd)
        if update_dist < 1e-16:
            break
        
    #print('niters:', iters)
    d, P = sort_eigs(np.diag(Ak), Vk)
    return d, P

A = np.random.randn(5, 5)
A = A.T @ A
d, P = eig_jacobi_naive(A)

for i in range(len(d)):
    print(metrics.tdist(A @ P[:, i], d[i] * P[:, i]))

print(metrics.tdist(np.linalg.inv(P) @ A @ P, np.diag(d)))
print(metrics.tdist(P @ np.diag(d) @ np.linalg.inv(P), A))

3.671505710473302e-09
1.4493498375546286e-09
1.0383639315528259e-09
6.820087138316276e-10
3.7619156770184175e-09
5.592487568235434e-09
5.592487513468515e-09


### Inplace algorithm

Instead of computing R and doing the matrix multiplication to update $A$ and $V$, it's possible to update them directly inplace, at a cost of $O(n)$.

### Update of A

$$A' = R^T A R$$

- $a'_{ii} = a_{ii} - ta_{ij}$
- $a'_{jj} = a_{jj} + ta_{ij}$
- $a'_{ik} = a'_{ki} = ca_{ik} - sa_{jk} \space (k \neq i, k \neq j)$
- $a'_{jk} = a'_{kj} = ca_{jk} + sa_{ik} \space (k \neq i, k \neq j)$
- $a'_{kl} = a_{kl} \space (k \neq i, l \neq j)$

Because $A$ is symmetric, it's possible to never read / write the lower or the upper half of $A$.

### Update of V

$$V' = V R$$

- $v'_{ki} = c v_{ki} - s v_{kj}$
- $v'_{kj} = c v_{kj} + s v_{ki}$
- $v'_{kl} = v_{kl} \space (l \neq i, l \neq j)$

In [11]:
def sort_eigs(d, P):
    dl = d.tolist()
    pl = list()
    for i in range(len(d)):
        pl.append(P[:, i])
    
    dl, pl = zip(*sorted(zip(dl, pl)))
    
    d = np.array(dl)
    P = np.array(pl).T
    
    return d, P

def update_a(A, i, j, c, s, t):
    A[i,i] = A[i,i] - t * A[i,j]
    A[j,j] = A[j,j] + t * A[i,j]
    
    for k in range(len(A)):
        aik = A[max(i,k), min(i,k)]
        ajk = A[max(j,k), min(j,k)]
        
        if i != k:
            A[max(i,k), min(i,k)] = c * aik - s * ajk
        if j != k:
            A[max(j,k), min(j,k)] = c * ajk + s * aik
    
    A[i,j] = 0
    
def update_AR(A, i, j, c, s):
    for k in range(len(A)):
        aki = A[k,i]
        akj = A[k,j]
        A[k,i] = c * aki - s * akj
        A[k,j] = c * akj + s * aki
        
    

def eig_jacobi(A):
    n = len(A)
    Ak = A.copy()
    Vk = np.eye(n)
    
    iters = 0
    while True:
        #Find position of sub-diagonal element with highest abs val
        Apr = np.abs(Ak - np.triu(Ak)).ravel()
        id0 = np.argmax(Apr)
        i0 = int(id0 / n)
        j0 = int(id0 % n)

        #compute c, s that will put 0 on A[i0,j0] and A[j0,i0]
        w = (Ak[j0,j0] - Ak[i0, i0]) / (2 * Ak[i0, j0])
        if w > 0:
            t = - w + np.sqrt(w*w + 1)
        else:
            t = - w - np.sqrt(w*w + 1)
        c = 1 / np.sqrt(1 + t*t)
        s = t / np.sqrt(1 + t*t)

        #Update Ak and Vk
        oldd = np.diag(Ak).copy()
        update_a(Ak, i0, j0, c, s, t)
        update_AR(Vk, i0, j0, c, s)
        iters += 1
        
        #Stop if diagonal almost didn't change
        newd = np.diag(Ak)
        update_dist = np.linalg.norm(oldd - newd)
        if update_dist < 1e-16:
            break
        
    #print('niters:', iters) 
    d, P = sort_eigs(np.diag(Ak), Vk)
    return d, P


A = np.random.randn(5, 5)
A = A.T @ A
d, P = eig_jacobi(A)

for i in range(len(d)):
    print(metrics.tdist(A @ P[:, i], d[i] * P[:, i]))
print(metrics.tdist(np.linalg.inv(P) @ A @ P, np.diag(d)))
print(metrics.tdist(P @ np.diag(d) @ np.linalg.inv(P), A))

2.081689462316654e-08
2.576268992201611e-10
3.5994813968192803e-10
2.081703929522544e-08
2.7892555823426863e-10
2.944428581353622e-08
2.9444286066685393e-08
