In [3]:
import sys
sys.path.append('..')

import numpy as np

import metrics

Let $A \in \mathbb{R}^{n*n}$

Let $v \in \mathbb{R}^{n}$. If there is a scalar $\lambda \in \mathbb{R}$ such that:

$$A v = \lambda v$$

Then $v$ is an eigenvector of $A$, and $\lambda$ is it's corresponding eigenvalue.  

$v$ is also called a right eigenvector, to differientate them from the left eigeinvectors, that satisfy the equation:

$$v^TA = \lambda v$$  

If $v$ is an eigeinvector, $\alpha v$, $\alpha \in \mathbb{R}$, is also an eigenvector, with the same eigeinvalue $\lambda$.  
That's why we are often only interested by the normalized eigenvectors

In [10]:
A = np.array([
    [2, -2, 1],
    [-1, 3, -1],
    [2, -4, 3]
])
d, V = np.linalg.eig(A)
d = d[0]
v = V[:, 0]

print(A @ v)
print(d * v)
print(metrics.tdist(A @ v, d * v))

v2 = -4.56 * v
print(A @ v2)
print(d * v2)
print(metrics.tdist(A @ v2, d * v2))

[-2.44948974  2.44948974 -4.89897949]
[-2.44948974  2.44948974 -4.89897949]
1.7763568394002505e-15
[ 11.16967323 -11.16967323  22.33934645]
[ 11.16967323 -11.16967323  22.33934645]
7.32410687763558e-15
