In [1]:
import sys
sys.path.append('..')

import numpy as np

import metrics

# Matrix similarity

Let $A$ and $B$ matrices of size $n*n$.  
$A$ and $B$ are similar if it exists an invertible matrix $P \in \mathbb{R}^{n*n}$ such that:
$$B = P^{-1}AP$$  

# Diagonalization

Let $A \in \mathbb{R}^{n*n}$
A is diagonalizable if it similar to a diagonal matrix.  
IE there is an invertible matrix $P \in \mathbb{R}^{n*n}$ such that $P^{-1}AP$ is diagonal.

The diagonilazation of matrix $A$ is:
$$P^{-1} A P = D$$
with $P \in \mathbb{R}^{n*n}$ is a matrix whose columns are the right eigenvectors of $A$.  
And $D \in \mathbb{R}^{n*n}$ a digonal matrix whose entries $D_{ii}$ is the eigeinvalue of $A$ corresponding to the eigeinvector $P_i$.  

The equation can be rewritten as:

$$A = PDP^{-1}$$

In [2]:
A = np.array([
    [1, 2, 1],
    [6, -1, 0],
    [-1, 2, 1]
])
d, P = np.linalg.eig(A)

print('A =\n', A)
print('P = \n', P)
print('diag(D)=\n', d)


D2 = np.linalg.inv(P) @ A @ P
print('P^-1AP=\n', D2)
print(metrics.tdist(np.diag(d), D2))

A2 = P @ np.diag(d) @ np.linalg.inv(P)
print('PDP^-1=\n', A2)
print(metrics.tdist(A, A2))

A =
 [[ 1  2  1]
 [ 6 -1  0]
 [-1  2  1]]
P = 
 [[ 0.60588985  0.28934634 -0.08122258]
 [ 0.73792101 -0.83016763 -0.41839386]
 [ 0.29727105  0.47655053  0.9046267 ]]
diag(D)=
 [ 3.92646107 -3.09123795  0.16477688]
P^-1AP=
 [[ 3.92646107e+00 -8.47397419e-16  5.54699765e-16]
 [ 3.69366844e-15 -3.09123795e+00  7.06300920e-16]
 [ 7.25290929e-16  3.97623940e-18  1.64776876e-01]]
4.431847301282925e-15
PDP^-1=
 [[ 1.00000000e+00  2.00000000e+00  1.00000000e+00]
 [ 6.00000000e+00 -1.00000000e+00  9.30119432e-16]
 [-1.00000000e+00  2.00000000e+00  1.00000000e+00]]
6.604835229600313e-15


# Square root of a matrix

Let $A$ and $B$ matrices of size $n*n$.  
Matrix $B$ is the square root of $A$ is $BB = A$  
The square root is denoted $B = A^{\frac{1}{2}}$  

A matrix may have several or no square root

If $A$ is diagonal, $B$ is a diagonal matrix whose entries are the square root of the diagonal entries of $A$

In [3]:
A = np.diag(np.random.randn(5)**2)
B = np.diag(np.sqrt(np.diag(A)))
print(metrics.tdist(A, B @ B))

0.0


If $A$ is diagonalizable with positive eigenvalues, the square root of $A$ is:

$$B = PD^{\frac{1}{2}}P^{-1}$$

In [4]:
A = np.array([
    [2, -2, 1],
    [-1, 3, -1],
    [2, -4, 3]
])
d, P = np.linalg.eig(A)

s = np.sqrt(d)
B = P @ np.diag(s) @ np.linalg.inv(P)
print(B)
print(metrics.tdist(B @ B, A))

[[ 1.28989795 -0.5797959   0.28989795]
 [-0.28989795  1.5797959  -0.28989795]
 [ 0.5797959  -1.15959179  1.5797959 ]]
1.900395703982448e-15


## Square root Inverse

$$A^{-\frac{1}{2}} = \text{inv}(A^{\frac{1}{2}})$$

$A^{-\frac{1}{2}}$ is the square root of $A^{-1}$:
$$A^{-\frac{1}{2}}A^{-\frac{1}{2}} = A^{-1}$$

If $A$ is diagonal, $A^{-\frac{1}{2}}$ is a diagonal matrix whose entries are the inverse square root of the diagonal entries of $A$

In [5]:
A = np.diag(3.8 * np.random.randn(5)**2 + 1.2)
B = np.diag(1 / np.sqrt(np.diag(A)))
print(metrics.tdist(np.linalg.inv(A), B @ B))

1.1443916996305594e-16


If $A$ is diagonalizable with positive eigenvalues, the inverse square root of $A$ is:

$$A^{-\frac{1}{2}} = PD^{-\frac{1}{2}}P^{-1}$$

In [6]:
A = np.array([
    [2, -2, 1],
    [-1, 3, -1],
    [2, -4, 3]
])
d, P = np.linalg.eig(A)

s = 1 / np.sqrt(d)
B = P @ np.diag(s) @ np.linalg.inv(P) 
print(B)
print(metrics.tdist(B @ B, np.linalg.inv(A)))

[[ 0.88164966  0.23670068 -0.11835034]
 [ 0.11835034  0.76329932  0.11835034]
 [-0.23670068  0.47340137  0.76329932]]
1.1025638216888958e-15


# Symmetric positive definite

Let $A$ a symmetric positive definite matrix. A is always diagonalizable:

$$P^T A P = D$$

With $P$, the marix of eigeinvectors, is an orthogonal matrix ($PP^T=P^TP=I$).

In [7]:
A = np.random.randn(4, 4)
A = A.T @ A
d, P = np.linalg.eigh(A)

print('A =\n', A)
print('P = \n', P)
print('diag(D)=\n', d)


D2 = np.linalg.inv(P) @ A @ P
print('P^-1AP=\n', D2)
print(metrics.tdist(np.diag(d), D2))

A2 = P @ np.diag(d) @ np.linalg.inv(P)
print('PDP^-1=\n', A2)
print(metrics.tdist(A, A2))

print(metrics.tdist(P @ P.T, np.eye(4)))
print(metrics.tdist(P.T @ P, np.eye(4)))

A =
 [[ 4.16076505 -1.62484051 -4.15315439 -1.20502683]
 [-1.62484051  2.09660811  1.66382534 -0.67298379]
 [-4.15315439  1.66382534  5.98969258  0.13351358]
 [-1.20502683 -0.67298379  0.13351358  1.99301582]]
P = 
 [[ 0.65363399  0.35018548 -0.27581825 -0.61160202]
 [ 0.42968083 -0.70998456 -0.48697488  0.27230824]
 [ 0.32468508  0.57461675 -0.13837068  0.7384096 ]
 [ 0.53171101 -0.20762381  0.81708831  0.08088539]]
diag(D)=
 [ 0.04935688  1.35462885  2.77826782 10.057828  ]
P^-1AP=
 [[ 4.93568797e-02  4.21858856e-16 -5.30656573e-16  2.39071534e-15]
 [ 8.59143361e-16  1.35462885e+00  1.16514511e-17 -2.55390863e-16]
 [-1.23300441e-16 -4.36303539e-16  2.77826782e+00 -3.96613237e-16]
 [ 2.57314451e-15  1.98218842e-15 -3.47607910e-16  1.00578280e+01]]
5.031148402184212e-15
PDP^-1=
 [[ 4.16076505 -1.62484051 -4.15315439 -1.20502683]
 [-1.62484051  2.09660811  1.66382534 -0.67298379]
 [-4.15315439  1.66382534  5.98969258  0.13351358]
 [-1.20502683 -0.67298379  0.13351358  1.99301582]]
4.308

# Computing: Diagonalization of Non-Symetric matrix

## Implicitly-Shifted QR

The Implicitly-shifted QR algorithm is a method to compute the eigenvalues and eigenvectors of any square matrix.  
It can only be applied to upper hessenberg matrices. The algorithm is in 3 steps:
- Convert $A$ to an upper hessenberg form
- Diagonalize the special matrix
- Get the diagonalization of $A$ from the previous step

### Convert a matrix to upper Hessenberg Form

A matrix in upper Hessenberg form is almost upper triangular, all entries below the first subdiagonal are zeroes:

$$
\begin{bmatrix}
   * & * & * & * & * \\
   * & * & * & * & * \\
   0 & * & * & * & * \\
   0 & 0 & * & * & * \\
   0 & 0 & 0 & * & *
\end{bmatrix}
$$

Let $A \in \mathbb{R}^{n*n}$, it can be brought to upper hessenberg form, it's decomposition is:

$$B = P A P^T$$

with $B \in \mathbb{R}^{n*n}$ matrix in upper hessenberg form, and $P \in \mathbb{R}^{n*n}$ orthogonal matrix.

Using a householder transformation, we can insert zeros below the diagonal with a matrix $P_1$. But multiplying by $P_1^T$ will reinsert values below the diagonal.  
But if $P_1$ Only insert zeros below the subdiagonal, multypling by $P_1^T$ will not affect the first column, and the zeros will remain:

$$
\begin{gather}
 P_1 A P_1^T=
\begin{bmatrix}
   * & * & * & * & * \\
   * & * & * & * & * \\
   0 & * & * & * & * \\
   0 & * & * & * & * \\
   0 & * & * & * & *
   \end{bmatrix}
\end{gather}
$$

With $n - 2$ transformations, it's possible to insert zeros below all the subdiagonal of $A$.

$$P_{n-2}P_{n-3}\text{...}P_2P_1AP_1^TP_2^T\text{...}P_{n-3}^TP_{n-2}^T = B$$

$$P = P_{n-2}P_{n-3}\text{...}P_2P_1$$

In [8]:
def house_vect(x):
    v = x.copy()
    v[0] = x[0] + np.sign(x[0]) * np.linalg.norm(x)
    return v
    
def house_mat(v):
    return np.eye(len(v)) - 2 * np.outer(v, v) / (v@v)


def hessen(A):
    n = len(A)
    Ak = A.copy()
    Q = np.eye(n)
    
    for j in range(n-2):
    
        v = house_vect(Ak[j+1:, j])
        P = np.eye(n)
        P[j+1:, j+1:] = house_mat(v)
        Q = P @ Q
        Ak = P @ Ak @ P.T
    
    return Ak, Q
    
    
A = np.random.randn(5, 5)
A2, P = hessen(A)

print(A2)

print(metrics.tdist(P @ P.T, np.eye(len(P))))
print(metrics.tdist(P.T @ P, np.eye(len(P))))
print(metrics.tdist(P @ A @ P.T, A2))
print(metrics.tdist(P.T @ A2 @ P, A))

[[ 5.43976240e-01 -8.40797305e-01  2.72400125e-03  6.50652296e-01
  -8.68543643e-01]
 [ 1.97171890e+00 -6.05955216e-01 -1.51083704e+00 -2.18501120e+00
  -7.51141299e-02]
 [ 3.90260043e-17 -1.21202380e+00  1.11348887e+00 -9.07008391e-01
  -3.58267576e-01]
 [-2.54092890e-17 -1.23385799e-16 -1.33984565e-01 -6.91678462e-01
  -1.12064726e+00]
 [-1.50383258e-17  9.28545057e-17  8.16344688e-18 -1.47640354e-01
   2.56646042e+00]]
4.855817650995959e-16
4.608855610169443e-16
9.389689344589599e-16
1.7250933163360054e-15


### Diagonalize an upper hessenberg matrix

In [69]:
def qr_algorithm(A, max_iters=1000):
    
    Ak = A.copy()
    V = np.eye(len(A))
    for k in range(max_iters):
        # Compute norm below diagonal
        lnorm = np.linalg.norm(Ak - np.triu(Ak))
        if lnorm < 1e-10: break
        
        Q, R = np.linalg.qr(Ak)
        Ak = R @ Q
        V = V @ Q
    
    print('iters:', k)
    
    return Ak, V

np.random.seed(15)

X1 = np.random.randn(5, 5)
X2 = np.diag(np.random.randn(len(X1)))
X = X1 @ X2 @ np.linalg.inv(X1)

A, _ = hessen(X)
#A = X

Ak, Q = qr_algorithm(A)

print(np.around(Ak, 2))
#print(np.around(Q, 2))

Ak2 = Q.T @ A @ Q
print(np.around(Ak2, 2))


d2, P2 = np.linalg.eig(A)

print(d2)
print(np.diag(Ak))

iters: 468
[[-1.86  1.43  2.97 -7.43 -2.69]
 [ 0.    1.5  -0.03 -0.35  1.43]
 [ 0.    0.    1.42 -0.04 -1.26]
 [ 0.    0.    0.    1.29  0.47]
 [-0.   -0.    0.   -0.   -1.17]]
[[-1.86  1.43  2.97 -7.43 -2.69]
 [ 0.    1.5  -0.03 -0.35  1.43]
 [ 0.    0.    1.42 -0.04 -1.26]
 [-0.   -0.    0.    1.29  0.47]
 [ 0.   -0.   -0.    0.   -1.17]]
[-1.85851316 -1.16718189  1.28993206  1.42489683  1.49656536]
[-1.85851316  1.49656536  1.42489683  1.28993206 -1.16718189]


### Get the diagonalization of A

Let $A \in \mathbb{R}^{n*n}$.  
Let $B \in \mathbb{R}^{n*n}$ upper hessenberg matrix:
$$B = QAQ^T$$
The diagonalization of $B$ is:
$$B = P_BD_BP_B^{-1}$$

$A$ and $B$ are similar, they have the same eigenvalues.

$$A = Q^TBQ = Q^TP_BD_BP_B^{-1}Q$$

The diagonalization of $A$ is:
$$A = PDP^{-1}$$
with $D = D_B$ and $P = Q^T P_B$

In [10]:
def my_eig(A):
    B, Q = hessen(A)
    db, Pb = np.linalg.eig(B)
    d = db
    P = Q.T @ Pb
    return d, P

X1 = np.random.randn(5, 5)
X2 = np.diag(np.random.randn(len(X1)))
A = X1 @ X2 @ np.linalg.inv(X1)
d, P = my_eig(A)

for i in range(len(d)):
    print(metrics.tdist(A @ P[:, i], d[i] * P[:, i]))

print(metrics.tdist(np.linalg.inv(P) @ A @ P, np.diag(d)))
print(metrics.tdist(P @ np.diag(d) @ np.linalg.inv(P), A))

5.896018613962273e-16
2.3889151536227185e-15
3.8762527077232024e-15
1.5549664902315766e-15
4.767520049740204e-15
2.2316656098934583e-14
1.8436639796905413e-14


## Naive diagonalization

### Explicit QR algorithm: Find eigenvalues

- Let $A_0 = A$
- Iterate:
    - Compute the $QR$ factorization of $A$: $A_k = Q_k R_k$
    - Let $A_{k+1} = Q_k R_k$

As $k \to \infty$, $A_k$ converges to the Schur form of $A$, an upper-triangular matrix.
$$A_{k+1} = Q_k^{-1}A_kQ_k$$
So $A$, $A_1$, ..., $A_k$ are all similar, and thus they share the same eigenvalues.  
The eigenvalues of the upper-triangular matrix $A_k$ lie on the diagionals, they are the eigenvalues of $A$

In [11]:
def qr_algorithm(A, max_iters=1000):
    
    Ak = A.copy()
    for k in range(max_iters):
        # Compute norm below diagonal
        lnorm = np.linalg.norm(Ak - np.triu(Ak))
        if lnorm < 1e-10: break
        
        Q, R = np.linalg.qr(Ak)
        Ak = R @ Q
    
    return np.diag(Ak)

A = np.array([
    [2, -2, 1],
    [-1, 3, -1],
    [2, -4, 3]
])

d = qr_algorithm(A)
d2, _ = np.linalg.eig(A)

print(d)
print(d2)
print(metrics.tdist(d, d2))

[6. 1. 1.]
[6. 1. 1.]
6.3873580624876566e-12


### Compute the eigenvectors from a corresponding eigenvalue

$$Av = \lambda v$$
$$(A - \lambda I)v = \vec{0}$$

An orthogonal basis of $\text{Null}(A - \lambda I)$ is a set of eigenvectors for the eigeinvalue $\lambda$

In [12]:
def sv_rank(s):
    i = 0
    while i < len(s):
        if s[i] * s[i] < 1e-12:
            break
        i += 1
    return i

def find_evec(A, d):
    amd = A - np.eye(len(A)) * d
    U, s, VT = np.linalg.svd(amd)
    r = sv_rank(s)
    return VT[r:].T

def my_eig(A):
    d = qr_algorithm(A)
    vects = None
    for i in range(len(d)):
        if i > 0 and (d[i] - d[i-1])**2 < 1e-12:
            continue
        
        v = find_evec(A, d[i])
        if vects is None:
            vects = v
        else:
            vects = np.concatenate((vects, v), axis = 1)
    return d, vects
    
    
A = np.array([
    [2, -2, 1],
    [-1, 3, -1],
    [2, -4, 3]
])
d, P = my_eig(A)

for i in range(len(d)):
    print(metrics.tdist(A @ P[:, i], d[i] * P[:, i]))

print(metrics.tdist(np.linalg.inv(P) @ A @ P, np.diag(d)))
print(metrics.tdist(P @ np.diag(d) @ np.linalg.inv(P), A))

1.4812106129721512e-12
3.3603528951155397e-12
6.352821333422274e-12
6.725357375506194e-12
8.730925457289283e-12


# Computing: Diagonalization of Symetric matrix

## Jacobi Eigenvalue algorithm

The Jacobi eigenvalue algorithm is an iterative method to compute the eigenvalues and eigenvectors of a real symmetric matrix

### General algorithm

Let $A \in \mathbb{R}^{n*n}$ symmetric matrix

Let $A_0 = A$

$$A_{k+1} = R_k^T A_k R_k$$

with $R_k \in \mathbb{R}^{n*n}$ a givens rotation matrix.

All $A_k$ are symmetric with $A_k \to \Lambda$ as $k \to \infty$  

The algorithm converges to the diagonalization of $A$:

$$\Lambda = A_k = R_{k-1}^TR_{k-2}^T\text{...}R_0^TAR_0\text{...}R_{k-2}R_{k-1}$$
$$\Lambda = V^T A V$$
with $V = R_0R_1\text{...}R_{k-1}$

### Givens step

$$A' = R^T A R$$

The goal is to insert a 0 into $A'_{ij}$ and $A'_{ji}$.  
$A_{ij}$ is selected at each step as the element wih highest manitude below (or above) the diagonal.  
$R$ is a givens matrix $G(i, j, c, s)$.
Results of one step:

- $a'_{ij} = a'_{ji} = (c^2 - s^2) a_{ij} + cs(a_{ii} - a_{jj})$
- $a'_{ii} = c^2a_{ii} + s^2a_{jj} - 2csa_{ij}$
- $a'_{jj} = c^2a_{jj} + s^2a_{ii} + 2csa_{ij}$
- $a'_{ik} = a'_{ki} = ca_{ik} - sa_{jk} \space (k \neq i, k \neq j)$
- $a'_{jk} = a'_{kj} = ca_{jk} + sa_{ik} \space (k \neq i, k \neq j)$
- $a'_{kl} = a_{kl} \space (k \neq i, l \neq j)$  


$c$ and $s$ are chosen by solving the equation
$$a'_{ij} = 0$$

Let $w = \frac{a_{jj} - a_{ii}}{2a_{ij}}$ and $t = \frac{s}{c}$

$t = -w \pm \sqrt{w^2 + 1}$

We choose the $t$ with the smaller absolute value:

$$
t = 
\begin{cases}
    -w + \sqrt{w^2 + 1} & \text{if } w \geq 0\\
    -w - \sqrt{w^2 + 1} & \text{if } w < 0
\end{cases}
$$

$$c = \frac{1}{\sqrt{1+t^2}}$$
$$s = \frac{t}{\sqrt{1+t^2}}$$

### Convergence

It converges to a diagonal matrix with a variable number of steps.  
The algorithm should be stopped when the diagonal elements of $A_k$ stops moving


### Rearrange eigenvalues and eigenvectors

The diagonal of $A_k$ contains the eigenvalues, and $V_k = R_0R_1\text{...}R_{k-1}$ the eigenvectors.  
The eigenvalues should be sorted by increasing order, and rearrange $V_k$ at the same time.

In [13]:
def given_mat(n, i, j, c, s):
    G = np.eye(n)
    G[i, i] = c
    G[j, j] = c
    G[i, j] = s
    G[j, i] = -s
    return G

def sort_eigs(d, P):
    dl = d.tolist()
    pl = list()
    for i in range(len(d)):
        pl.append(P[:, i])
    
    dl, pl = zip(*sorted(zip(dl, pl)))
    
    d = np.array(dl)
    P = np.array(pl).T
    
    return d, P
    

def eig_jacobi_naive(A):
    n = len(A)
    Ak = A.copy()
    Vk = np.eye(n)
    
    iters = 0
    while True:
        #Find position of sub-diagonal element with highest abs val
        Apr = np.abs(Ak - np.triu(Ak)).ravel()
        id0 = np.argmax(Apr)
        i0 = int(id0 / n)
        j0 = int(id0 % n)

        #compute c, s that will put 0 on A[i0,j0] and A[j0,i0]
        w = (Ak[j0,j0] - Ak[i0, i0]) / (2 * Ak[i0, j0])
        if w > 0:
            t = - w + np.sqrt(w*w + 1)
        else:
            t = - w - np.sqrt(w*w + 1)
        c = 1 / np.sqrt(1 + t*t)
        s = t / np.sqrt(1 + t*t)

        #Update Ak and Vk
        oldd = np.diag(Ak)
        R = given_mat(n, i0, j0, c, s)
        Ak = R.T @ Ak @ R
        Vk = Vk @ R
        iters += 1
        
        #Stop if diagonal almost didn't change
        newd = np.diag(Ak)
        update_dist = np.linalg.norm(oldd - newd)
        if update_dist < 1e-16:
            break
        
    #print('niters:', iters)
    d, P = sort_eigs(np.diag(Ak), Vk)
    return d, P

A = np.random.randn(5, 5)
A = A.T @ A
d, P = eig_jacobi_naive(A)

for i in range(len(d)):
    print(metrics.tdist(A @ P[:, i], d[i] * P[:, i]))

print(metrics.tdist(np.linalg.inv(P) @ A @ P, np.diag(d)))
print(metrics.tdist(P @ np.diag(d) @ np.linalg.inv(P), A))

3.175458931258127e-08
8.15960973091763e-09
3.019101309715801e-09
3.26453136358311e-08
5.679507902062138e-10
4.6369033809466186e-08
4.6369033239558954e-08


### Inplace algorithm

Instead of computing R and doing the matrix multiplication to update $A$ and $V$, it's possible to update them directly inplace, at a cost of $O(n)$.

### Update of A

$$A' = R^T A R$$

- $a'_{ii} = a_{ii} - ta_{ij}$
- $a'_{jj} = a_{jj} + ta_{ij}$
- $a'_{ik} = a'_{ki} = ca_{ik} - sa_{jk} \space (k \neq i, k \neq j)$
- $a'_{jk} = a'_{kj} = ca_{jk} + sa_{ik} \space (k \neq i, k \neq j)$
- $a'_{kl} = a_{kl} \space (k \neq i, l \neq j)$

Because $A$ is symmetric, it's possible to never read / write the lower or the upper half of $A$.

### Update of V

$$V' = V R$$

- $v'_{ki} = c v_{ki} - s v_{kj}$
- $v'_{kj} = c v_{kj} + s v_{ki}$
- $v'_{kl} = v_{kl} \space (l \neq i, l \neq j)$

In [14]:
def sort_eigs(d, P):
    dl = d.tolist()
    pl = list()
    for i in range(len(d)):
        pl.append(P[:, i])
    
    dl, pl = zip(*sorted(zip(dl, pl)))
    
    d = np.array(dl)
    P = np.array(pl).T
    
    return d, P

def update_a(A, i, j, c, s, t):
    A[i,i] = A[i,i] - t * A[i,j]
    A[j,j] = A[j,j] + t * A[i,j]
    
    for k in range(len(A)):
        aik = A[max(i,k), min(i,k)]
        ajk = A[max(j,k), min(j,k)]
        
        if i != k:
            A[max(i,k), min(i,k)] = c * aik - s * ajk
        if j != k:
            A[max(j,k), min(j,k)] = c * ajk + s * aik
    
    A[i,j] = 0
    
def update_AR(A, i, j, c, s):
    for k in range(len(A)):
        aki = A[k,i]
        akj = A[k,j]
        A[k,i] = c * aki - s * akj
        A[k,j] = c * akj + s * aki
        
    

def eig_jacobi(A):
    n = len(A)
    Ak = A.copy()
    Vk = np.eye(n)
    
    iters = 0
    while True:
        #Find position of sub-diagonal element with highest abs val
        Apr = np.abs(Ak - np.triu(Ak)).ravel()
        id0 = np.argmax(Apr)
        i0 = int(id0 / n)
        j0 = int(id0 % n)

        #compute c, s that will put 0 on A[i0,j0] and A[j0,i0]
        w = (Ak[j0,j0] - Ak[i0, i0]) / (2 * Ak[i0, j0])
        if w > 0:
            t = - w + np.sqrt(w*w + 1)
        else:
            t = - w - np.sqrt(w*w + 1)
        c = 1 / np.sqrt(1 + t*t)
        s = t / np.sqrt(1 + t*t)

        #Update Ak and Vk
        oldd = np.diag(Ak).copy()
        update_a(Ak, i0, j0, c, s, t)
        update_AR(Vk, i0, j0, c, s)
        iters += 1
        
        #Stop if diagonal almost didn't change
        newd = np.diag(Ak)
        update_dist = np.linalg.norm(oldd - newd)
        if update_dist < 1e-16:
            break
        
    #print('niters:', iters) 
    d, P = sort_eigs(np.diag(Ak), Vk)
    return d, P


A = np.random.randn(5, 5)
A = A.T @ A
d, P = eig_jacobi(A)

for i in range(len(d)):
    print(metrics.tdist(A @ P[:, i], d[i] * P[:, i]))
print(metrics.tdist(np.linalg.inv(P) @ A @ P, np.diag(d)))
print(metrics.tdist(P @ np.diag(d) @ np.linalg.inv(P), A))

1.3650974180029193e-08
2.3609938642612105e-09
1.9903807493380025e-09
2.8152852880587198e-08
2.465632328219089e-08
3.9955004654167864e-08
3.995500488298265e-08
