In [1]:
import sys
sys.path.append('../../pyutils')

import numpy as np

import metrics

# Definition

Let $A \in \mathbb{R}^{n*n}$

Let $v \in \mathbb{R}^{n}$. If there is a scalar $\lambda \in \mathbb{R}$ such that:

$$A v = \lambda v$$

Then $v$ is an eigenvector of $A$, and $\lambda$ is it's corresponding eigenvalue.  

$v$ is also called a right eigenvector, to differientate them from the left eigeinvectors, that satisfy the equation:

$$v^TA = \lambda v$$  

If $v$ is an eigeinvector, $\alpha v$, $\alpha \in \mathbb{R}$, is also an eigenvector, with the same eigeinvalue $\lambda$.  
That's why we are often only interested by the normalized eigenvectors

In [2]:
A = np.array([
    [2, -2, 1],
    [-1, 3, -1],
    [2, -4, 3]
])
d, V = np.linalg.eig(A)
print(d)
print(V)
d = d[0]
v = V[:, 0]

print(A @ v)
print(d * v)
print(metrics.tdist(A @ v, d * v))

v2 = -4.56 * v
print(A @ v2)
print(d * v2)
print(metrics.tdist(A @ v2, d * v2))

[6. 1. 1.]
[[-0.40824829 -0.50222833  0.86820728]
 [ 0.40824829  0.17255747  0.48545624]
 [-0.81649658  0.84734327  0.10270521]]
[-2.44948974  2.44948974 -4.89897949]
[-2.44948974  2.44948974 -4.89897949]
1.7763568394002505e-15
[ 11.16967323 -11.16967323  22.33934645]
[ 11.16967323 -11.16967323  22.33934645]
7.32410687763558e-15


# Power method

The power method is an algorithm to find the eigenvalue of a matrix $A \in \mathbb{R}^{n*n}$ with the greatest magnitude, and its corresponding eigenvector

Let $v_0$ an approximation of the eigenvector. Define the recursion:
$$v_{k+1} = \frac{Av_k}{||Av_k||}$$
Thus, $v_k$ can be defined as:
$$v_k = \frac{A^k v_0}{||A^k v_0||}$$

It can be shown that if $A$ is diagonalizable, $v_k$ converges to the eigenvector corresponding to the eigenvalue with the greatest magnitude.

The corresponding eigenvalue can be estimated with the Rayleigh quotient.

# Rayleigh quotient

Let $x \in \mathbb{R}^n$ and $M \in \mathbb{R}^{n*n}$. The Rayleigh quotient $R(M,x)$ is defined as:
$$R(M,x) = \frac{x^TMx}{x^Tx}$$

The Rayleigh quotient reaches its minimum value $\lambda_\min$ (the smallest eigenvalue of $M$) when $x = v_\min$ (the corresponding eigenvector).  
Similarly, the Rayleigh quotient reaches its maximum value $\lambda_\max$ (the largest eigenvalue of $M$) when $x = v_\max$ (the corresponding eigenvector).

In [3]:
def power_method(A, tol=1e-16):
    N = len(A)
    v = np.random.rand(N)
    
    its = 0
    while True:
        v1 = A @ v
        v1 /= np.linalg.norm(v1)
        
        its += 1
        if (v - v1) @ (v - v1) < tol:
            break
        v = v1
        
    #print(its)
    return v1 @ A @ v1, v1
    
A = np.array([
    [2, -2, 1],
    [-1, 3, -1],
    [2, -4, 3]
])
d, v = power_method(A)
print(d)
print(v)

5.999999998930137
[ 0.40824829 -0.40824829  0.81649658]
