In [1]:
import sys
sys.path.append('../../pyutils')

import numpy as np
import scipy.linalg

import metrics

np.random.seed(12)

# Solve triangular systems

## Backward subtitution

Let $A$ upper triangular matrix of size $n*n$ and $b$ vector of size $n$.  
Find vector $x$ of size $n$ such that $Ax=b$

In [2]:
def solve_upper(A, b):
    n = A.shape[0]
    x = np.empty((n))
    
    for i in reversed(range(n)): #i = n-1 -> 0
        val = b[i]
        for j in reversed(range(i + 1, n)): #j = n - 1 -> i + 1
            val -= A[i, j] * x[j]
        x[i] = val / A[i, i]
    
    return x

In [3]:
A = np.triu(np.random.randn(4, 4))
b = np.random.randn(4)

x = solve_upper(A, b)
x_sol = scipy.linalg.solve_triangular(A, b)

print(x)
print(x_sol)
print(metrics.tdist(x, x_sol))
print(metrics.tdist(A @ x, b))

[-28.39667586   1.35094696  -6.10511951  -9.90420428]
[-28.39667586   1.35094696  -6.10511951  -9.90420428]
3.5596458096434965e-15
2.482534153247273e-16


Can be extended to matrix systems.  
Let $A$ upper triangular matrix of size $n*n$ and $b$ vector of size $n*p$.  
Find vector $x$ of size $n*p$ such that $Ax=b$

In [4]:
def solve_uppers(A, B):
    n = A.shape[0]
    X = np.empty((n, B.shape[1]))
    
    for e in range(B.shape[1]):
        for i in reversed(range(n)): #i = n-1 -> 0
            val = B[i, e]
            for j in reversed(range(i + 1, n)): #j = n - 1 -> i + 1
                val -= A[i, j] * X[j, e]
            X[i, e] = val / A[i, i]
    
    return X

In [5]:
A = np.triu(np.random.randn(4, 4))
b = np.random.randn(4, 3)

x = solve_uppers(A, b)
x_sol = scipy.linalg.solve_triangular(A, b)

print(x)
print(x_sol)
print(metrics.tdist(x, x_sol))
print(metrics.tdist(A @ x, b))

[[  6.6015892    0.3229454  -23.51865406]
 [  8.23144716   1.8955736  -23.43640668]
 [ -1.93518192  -0.48665919  -1.63202372]
 [ -7.98978433  -1.56882848  30.60415431]]
[[  6.6015892    0.3229454  -23.51865406]
 [  8.23144716   1.8955736  -23.43640668]
 [ -1.93518192  -0.48665919  -1.63202372]
 [ -7.98978433  -1.56882848  30.60415431]]
8.940742581002926e-15
5.9486356777158e-15


It's possible to find the inverse of an upper triangular matrix by solving $AX = B$ for $B = I$.  
$X = A^{-1}$

In [6]:
def inv_upper(A):
    return solve_uppers(A, np.eye(A.shape[0]))

In [7]:
A = np.triu(np.random.randn(4, 4))
Ai = inv_upper(A)
Ai_sol = np.linalg.inv(A)

print(Ai)
print(Ai_sol)
print(metrics.tdist(Ai, Ai_sol))
print(metrics.tdist(A @ Ai, np.eye(4)))
print(metrics.tdist(Ai @ A, np.eye(4)))

[[-0.3177209   0.08041446 -0.13109328  0.38506939]
 [ 0.          0.47295988 -9.37013626 -1.94565064]
 [ 0.          0.         19.79303354  4.18568414]
 [ 0.          0.          0.          1.47534818]]
[[-0.3177209   0.08041446 -0.13109328  0.38506939]
 [ 0.          0.47295988 -9.37013626 -1.94565064]
 [ 0.          0.         19.79303354  4.18568414]
 [ 0.          0.          0.          1.47534818]]
5.721958498152797e-17
9.378457834678574e-16
4.1293473805404105e-16


## Forward subtitution

Let $A$ lower triangular matrix of size $n*n$ and $b$ vector of size $n$.  
Find vector $x$ of size $n$ such that $Ax=b$

In [8]:
def solve_lower(A, b):
    n = A.shape[0]
    x = np.empty((n))
    
    for i in range(n): #i = 0 ->n-1
        val = b[i]
        for j in range(i): #j = 0 -> i - 1
            val -= A[i, j] * x[j]
        x[i] = val / A[i, i]
    
    return x

In [9]:
A = np.tril(np.random.randn(4, 4))
b = np.random.randn(4)

x = solve_lower(A, b)
x_sol = scipy.linalg.solve_triangular(A, b, lower=True)

print(x)
print(x_sol)
print(metrics.tdist(x, x_sol))
print(metrics.tdist(A @ x, b))

[-2.40871187  4.45622536  7.28112487 -6.97363827]
[-2.40871187  4.45622536  7.28112487 -6.97363827]
8.881784197001252e-16
4.685680459230494e-16


Can be extended to matrix systems.  
Let $A$ lower triangular matrix of size $n*n$ and $b$ vector of size $n*p$.  
Find vector $x$ of size $n*p$ such that $Ax=b$

In [10]:
def solve_lowers(A, B):
    n = A.shape[0]
    X = np.empty((n, B.shape[1]))
    
    for e in range(B.shape[1]):
        for i in range(n): #i = 0 ->n-1
            val = B[i, e]
            for j in range(i): #j = 0 -> i - 1
                val -= A[i, j] * X[j, e]
            X[i, e] = val / A[i, i]
    
    return X

In [11]:
A = np.tril(np.random.randn(4, 4))
b = np.random.randn(4, 3)

x = solve_lowers(A, b)
x_sol = scipy.linalg.solve_triangular(A, b, lower=True)

print(x)
print(x_sol)
print(metrics.tdist(x, x_sol))
print(metrics.tdist(A @ x, b))

[[-7.46732472e-01 -6.53122733e-01  8.71301518e-03]
 [-1.20228892e+00 -1.55909980e+00 -1.57507954e+00]
 [-2.39393459e+00  7.03995217e-02  1.58297982e+01]
 [-1.51484917e+01 -7.16689607e-01  2.83918290e+01]]
[[-7.46732472e-01 -6.53122733e-01  8.71301518e-03]
 [-1.20228892e+00 -1.55909980e+00 -1.57507954e+00]
 [-2.39393459e+00  7.03995217e-02  1.58297982e+01]
 [-1.51484917e+01 -7.16689607e-01  2.83918290e+01]]
4.1694611933691605e-15
5.775561153410717e-16


It's possible to find the inverse of a lower triangular matrix by solving $AX = B$ for $B = I$.  
$X = A^{-1}$

In [12]:
def inv_lower(A):
    return solve_lowers(A, np.eye(A.shape[0]))

In [13]:
A = np.tril(np.random.randn(4, 4))
Ai = inv_lower(A)
Ai_sol = np.linalg.inv(A)

print(Ai)
print(Ai_sol)
print(metrics.tdist(Ai, Ai_sol))
print(metrics.tdist(A @ Ai, np.eye(4)))
print(metrics.tdist(Ai @ A, np.eye(4)))

[[  0.73214326   0.           0.           0.        ]
 [  1.04437117   1.03546858   0.           0.        ]
 [-70.15319675 -40.19903349  26.55621886   0.        ]
 [ 22.36283188  13.09996667  -8.49524346  -0.66090042]]
[[ 7.32143256e-01 -1.45809375e-16  7.89821193e-17  0.00000000e+00]
 [ 1.04437117e+00  1.03546858e+00  1.45558653e-16  0.00000000e+00]
 [-7.01531967e+01 -4.01990335e+01  2.65562189e+01 -0.00000000e+00]
 [ 2.23628319e+01  1.30999667e+01 -8.49524346e+00 -6.60900416e-01]]
3.5752792860319764e-14
1.4724178093283334e-15
2.4710434342335953e-14


The inverse of a diagonal matrix is the matrix with all elements in the diagonal inversed.

In [14]:
def inv_diag(A):
    return np.diag(1. / np.diag(A))

A = np.diag(np.random.randn(3))
Ai = inv_diag(A)
Ai_sol = np.linalg.inv(A)

print(A)
print(Ai)
print(Ai_sol)
print(metrics.tdist(Ai, Ai_sol))
print(metrics.tdist(A @ Ai, np.eye(3)))
print(metrics.tdist(Ai @ A, np.eye(3)))

[[-0.76353049  0.          0.        ]
 [ 0.          0.24920321  0.        ]
 [ 0.          0.         -1.58980861]]
[[-1.3097054   0.          0.        ]
 [ 0.          4.01278941  0.        ]
 [ 0.          0.         -0.62900653]]
[[-1.3097054  -0.         -0.        ]
 [ 0.          4.01278941  0.        ]
 [-0.         -0.         -0.62900653]]
0.0
0.0
0.0
